"""Render figures for an SBM run.

Reads ``<run_dir>/model.npy`` and saves figures into ``<run_dir>/figs/``.
Re-running rebuilds everything inside ``figs/``; the synthetic alignment
needed by some figures is supplied separately via
``--synthetic-alignment`` (typically generated by
``scripts/sample_sbm.sh``).

By default only ``coupling_evol`` is rendered — it is the only figure
that does not require a synthetic alignment. To render diagnostic
figures that compare data statistics to a model-sampled MSA (``freq``,
``pair_freq``, ``corr3``, ``pca``, ``energy``, ``similarity``,
``diversity``, ``length``), pass them explicitly via ``--figs`` *and*
provide ``--synthetic-alignment PATH`` (an alignment ``.npy`` produced
by ``scripts/sample_sbm.py``).

Reuses ``SBM.utils.utils_plot.plot_stats`` for the nine plot modes.
PDFs go through ``lab_plotting.save_figure`` (sibling script in
``scripts/``) so the git commit, calling-script path, and run id end up
in the PDF metadata. ``figs/inputs/sources.json`` records the absolute
paths and sha256s of the model and synthetic-alignment files that fed
the figures, without duplicating their bytes.

Usage::

    python scripts/render_figures.py <run_dir> \\
        [--synthetic-alignment PATH] [--figs name [name ...]]
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import logging
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

import SBM.provenance as provenance
import SBM.utils.utils as ut
import SBM.utils.utils_plot as up

# scripts/lab_plotting.py is a sibling, not a package module. Add this
# script's directory to sys.path so the plain `import lab_plotting` works
# regardless of whether the user `cd`'s into scripts/ first.
_SCRIPT_DIR = Path(__file__).resolve().parent
if str(_SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPT_DIR))
import lab_plotting  # noqa: E402

log = logging.getLogger(__name__)

#: All plot modes implemented in ``utils_plot.plot_stats``. Order is the
#: rendering order; figure files use these exact names as the stem.
ALL_FIGS: tuple[str, ...] = (
    "freq",
    "pair_freq",
    "corr3",
    "pca",
    "energy",
    "coupling_evol",
    "similarity",
    "diversity",
    "length",
)

#: Figures rendered by default. Restricted to those that need no
#: synthetic alignment, since sampling from the trained model is a
#: separate downstream step. Everything else in ALL_FIGS is opt-in.
DEFAULT_FIGS: tuple[str, ...] = ("coupling_evol",)

# ``utils_plot.plot_stats`` selects modes by string. Map our snake_case
# figure names to the ``plot=...`` strings that file expects.
_PLOT_MODES: dict[str, str] = {
    "freq": "Freq",
    "pair_freq": "Pair_freq",
    "corr3": "Corr3",
    "pca": "PCA",
    "energy": "Energy",
    "coupling_evol": "Coupling_evol",
    "similarity": "Similarity",
    "diversity": "Diversity",
    "length": "Length",
}

#: Figures whose data needs ``compute_stats(...)`` output.
_NEEDS_STATS: frozenset[str] = frozenset({"freq", "pair_freq", "corr3"})

#: Figures whose data needs an artificial alignment.
_NEEDS_ALIGN_MOD: frozenset[str] = frozenset(
    {"pca", "energy", "similarity", "diversity", "length"}
)

#: Figures that need a real test set (i.e. ``Test/Train=1`` at training).
#: ``compute_stats`` handles the missing case (it substitutes Train for
#: Test internally), so the freq/pair_freq/corr3 plots work without a
#: test set; the others read ``output["Test"]`` directly and crash.
_NEEDS_TEST: frozenset[str] = frozenset({"energy", "similarity", "diversity", "length"})

#: Mode → preferred sampling temperature. Mirrors sample_sbm.py's table.
#: Used by ``_autodiscover_synthetic`` to disambiguate when multiple
#: alignments live under ``<run_dir>/synthetic/``.
_MODE_TEMPERATURE: dict[str, float] = {"BM": 0.75, "SBM": 1.0}


def _load_model(run_dir: Path) -> dict:
    model_path = run_dir / "model.npy"
    if not model_path.is_file():
        raise FileNotFoundError(
            f"no model at {model_path} — pass a run dir produced by "
            "scripts/train_sbm.py"
        )
    return np.load(model_path, allow_pickle=True).item()


def _read_seed(run_dir: Path) -> int | None:
    """Pull the master seed from the run's manifest, if present."""
    manifest_path = run_dir / "manifest.json"
    if not manifest_path.is_file():
        return None
    seed = json.loads(manifest_path.read_text(encoding="utf-8")).get("seed")
    return int(seed) if seed is not None else None


def _seed_global_rng(seed: int | None) -> None:
    """Seed numpy's global RNG so the unseeded ``np.random.choice`` calls
    inside ``compute_stats`` and the PCA renderer produce reproducible
    subsamples. No-op if the run was started without ``--seed``.
    """
    if seed is None:
        log.info("no seed in manifest; figure subsamples will be nondeterministic")
        return
    np.random.seed(seed)


def _autodiscover_synthetic(run_dir: Path) -> Path | None:
    """Pick a synthetic alignment from ``<run_dir>/synthetic/``.

    Selection rule (matches the docs):
      * 0 candidates → return ``None`` (caller decides whether that's an error).
      * 1 candidate → return it.
      * Multiple → prefer the file whose temperature token matches the
        run's mode default (BM=0.75, SBM=1.0). If none match (or the
        mode can't be read), fall back to the newest by mtime and emit
        a warning naming the choice.
    """
    syn_dir = run_dir / "synthetic"
    if not syn_dir.is_dir():
        return None
    candidates = sorted(syn_dir.glob("*.npy"))
    if not candidates:
        return None
    if len(candidates) == 1:
        return candidates[0]

    mode = None
    manifest_path = run_dir / "manifest.json"
    if manifest_path.is_file():
        try:
            mode = (
                json.loads(manifest_path.read_text(encoding="utf-8"))
                .get("options", {})
                .get("Model")
            )
        except (json.JSONDecodeError, OSError) as exc:
            log.warning("could not read mode from %s: %s", manifest_path, exc)
    mode_norm = str(mode).upper() if mode is not None else ""
    preferred_T = _MODE_TEMPERATURE.get(mode_norm)
    if preferred_T is not None:
        token = f"align_T{_format_temperature(preferred_T)}_"
        for c in candidates:
            if c.name.startswith(token):
                return c

    newest = max(candidates, key=lambda p: p.stat().st_mtime)
    log.warning(
        "multiple alignments under %s/; no T=%s match, using newest: %s",
        syn_dir,
        _format_temperature(preferred_T) if preferred_T is not None else "?",
        newest.name,
    )
    return newest


def _format_temperature(T: float) -> str:
    """Filename-safe, lossless-within-reason temperature token.

    Uses ``%g`` formatting with enough precision to avoid collisions for
    physically reasonable temperatures: ``T=1.0`` → ``"1"``,
    ``T=0.75`` → ``"0.75"``, ``T=0.001`` → ``"0.001"``.
    Mirrors the formatter in ``sample_sbm.py``; both must agree so that
    ``_autodiscover_synthetic`` can match filenames.
    """
    return f"{T:.10g}"


def _load_align_mod(path: Path, model: dict) -> np.ndarray:
    """Load a synthetic alignment from disk and validate against the model.

    Sampling is now a separate step (``scripts/sample_sbm.py``); this script
    only consumes the alignment file. We check ``L`` matches the training
    MSA and warn on mismatched ``N`` (similarity / diversity histograms
    visually compare distributions, so unequal supports are workable but
    worth flagging).
    """
    if not path.is_file():
        raise FileNotFoundError(
            f"synthetic alignment not found at {path}. Generate one with "
            "scripts/sample_sbm.sh <run_dir> first."
        )
    align_mod = np.load(path)
    train_align = model["align"]
    if not np.issubdtype(align_mod.dtype, np.integer):
        raise ValueError(
            f"synthetic alignment {path} has dtype {align_mod.dtype}; "
            "expected an integer alignment (output of sample_sbm.py)"
        )
    if align_mod.ndim != 2 or align_mod.shape[1] != train_align.shape[1]:
        raise ValueError(
            f"synthetic alignment shape {align_mod.shape} does not match "
            f"model L={train_align.shape[1]} (training shape {train_align.shape})"
        )
    if align_mod.shape[0] != train_align.shape[0]:
        log.warning(
            "synthetic alignment has N=%d but training MSA has N=%d — "
            "histogram supports will differ",
            align_mod.shape[0],
            train_align.shape[0],
        )
    log.info("loaded synthetic alignment %s (shape %s)", path, align_mod.shape)
    return align_mod


def _ensure_stats(model: dict, align_mod: np.ndarray, figs_inputs_dir: Path) -> dict:
    """Compute (or load cached) train/test/artificial statistics dict.

    Cached at ``figs/inputs/stats.npy``. ``compute_stats`` is the slowest
    bit because of the 3-point correlation tensor; the cache lets a direct
    re-invocation of this script reuse the stats. ``render_sbm.sh`` blows
    away ``figs/`` first so it always recomputes — desirable when the
    synthetic alignment may have changed.
    """
    cache = figs_inputs_dir / "stats.npy"
    if cache.is_file():
        log.info("loading cached stats from %s", cache)
        return np.load(cache, allow_pickle=True).item()
    figs_inputs_dir.mkdir(parents=True, exist_ok=True)
    log.info("computing stats (Train, Test, Artificial; this is the slow part)")
    stats = ut.compute_stats(model, align_mod)
    np.save(cache, stats)
    return stats


def _write_sources_json(
    figs_inputs_dir: Path,
    *,
    run_dir: Path,
    model_path: Path,
    align_path: Path | None,
    figures: list[str],
) -> None:
    """Record what fed the figures: paths + sha256s of model.npy and the
    synthetic alignment used (if any). The data files themselves stay
    where they are — model.npy at the run-dir top level, the alignment
    under synthetic/ — so this is a pointer file, not a copy.
    """
    figs_inputs_dir.mkdir(parents=True, exist_ok=True)
    sources: dict = {
        "schema_version": 1,
        "run_id": run_dir.name,
        "run_dir": str(run_dir),
        "rendered_at": dt.datetime.now(dt.timezone.utc).isoformat(),
        "figures": list(figures),
        "model": {
            "path": str(model_path),
            "sha256": provenance.file_sha256(model_path),
        },
        "synthetic_alignment": (
            {
                "path": str(align_path),
                "sha256": provenance.file_sha256(align_path),
            }
            if align_path is not None
            else None
        ),
        "code": {
            "git_commit": provenance.git_commit(),
            "git_dirty": provenance.git_dirty(),
            "git_branch": provenance.git_branch(),
        },
    }
    out_path = figs_inputs_dir / "sources.json"
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(sources, f, indent=2, ensure_ascii=False)
        f.write("\n")


def _patch_legacy_options(model: dict) -> None:
    """``utils_plot.plot_stats`` reads ``output["options"]`` (not split
    into options0/options1) — and the Coupling_evol mode specifically
    reads ``options["n_states"]`` and ``options["m"]``. Older models
    written by hand had a single ``options`` key; train_sbm.py writes
    ``options0`` + ``options1``. Build a flat alias that covers both
    cases without modifying utils_plot.py.
    """
    if "options" in model:
        return
    flat: dict = {}
    flat.update(model.get("options0", {}))
    flat.update(model.get("options1", {}))
    # ``n_states`` was the legacy name for ``N_chains``; preserve back-compat
    # for the Coupling_evol title without inventing a new key elsewhere.
    flat.setdefault("n_states", flat.get("N_chains"))
    model["options"] = flat


def _rasterize_dense_artists(fig: plt.Figure) -> None:
    """Rasterize Line2D / scatter artists in-place.

    ``utils_plot.plot_stats`` builds correlation scatters with millions of
    points (``pair_freq``: ~L(L-1)/2 * q^2 = ~2M; ``corr3`` is worse).
    Rendered as vectors, the resulting PDFs are tens of MB. Rasterizing
    keeps PDF size reasonable while leaving axes / labels / titles as
    real text. ``savefig(..., dpi=...)`` controls the raster resolution
    (we leave matplotlib's default of 100, which is fine for the
    correlation-cloud visual).
    """
    for ax in fig.axes:
        # Flatten everything plottable; keep text untouched.
        for artist in ax.lines + ax.collections + ax.patches:
            artist.set_rasterized(True)


def _render_one(
    name: str,
    model: dict,
    stats: dict | None,
    figs_dir: Path,
    *,
    run_id: str,
) -> list[Path]:
    """Call ``plot_stats(plot=mode)`` and save every Figure it created.

    PCA produces two figures (natural / artificial); we save both with
    a numeric suffix. Other modes produce one.
    """
    mode = _PLOT_MODES[name]
    before = set(plt.get_fignums())
    up.plot_stats(model, stats or {}, plot=mode)
    after = set(plt.get_fignums())
    new_fignums = sorted(after - before)
    if not new_fignums:
        log.warning("plot_stats(plot=%r) produced no figure", mode)
        return []
    figs_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    multi = len(new_fignums) > 1
    for i, n in enumerate(new_fignums):
        fig = plt.figure(n)
        _rasterize_dense_artists(fig)
        stem = f"{name}_{i}" if multi else name
        path = figs_dir / f"{stem}.pdf"
        # Use 'Keywords' for the run id — matplotlib's PDF backend
        # filters out unknown infodict keys with a warning, so we stick
        # to a standard one.
        lab_plotting.save_figure(
            fig,
            path,
            script_path=Path(__file__),
            extra_metadata={"Keywords": f"sbm_run_id={run_id}"},
        )
        plt.close(fig)
        written.append(path)
    return written


def _filter_renderable(model: dict, requested: list[str]) -> list[str]:
    """Drop figures whose required data isn't present in the model.

    Currently: anything in ``_NEEDS_TEST`` is dropped if the model was
    trained with ``Test/Train=0`` (so ``output["Test"]`` is None).
    """
    keep: list[str] = []
    has_test = model.get("Test") is not None
    for name in requested:
        if name in _NEEDS_TEST and not has_test:
            log.warning("skipping %r: this run has no test set (Test/Train=0)", name)
            continue
        keep.append(name)
    return keep


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Render figures for an SBM run.")
    parser.add_argument(
        "run_dir",
        type=Path,
        help="path to a run directory produced by scripts/train_sbm.py",
    )
    parser.add_argument(
        "--synthetic-alignment",
        type=Path,
        default=None,
        help=(
            "path to a synthetic alignment .npy (produced by "
            "scripts/sample_sbm.py). Required when --figs includes any of: "
            + ", ".join(sorted(_NEEDS_ALIGN_MOD | _NEEDS_STATS))
        ),
    )
    parser.add_argument(
        "--figs",
        nargs="+",
        choices=ALL_FIGS,
        default=list(DEFAULT_FIGS),
        metavar="NAME",
        help=(
            "which figures to render. Default: "
            + ", ".join(DEFAULT_FIGS)
            + " (the only figures that don't require a synthetic "
            "alignment). Other choices, all of which need "
            "--synthetic-alignment: "
            + ", ".join(f for f in ALL_FIGS if f not in DEFAULT_FIGS)
            + "."
        ),
    )
    args = parser.parse_args(argv)

    logging.basicConfig(level=logging.INFO, format="%(message)s")

    run_dir: Path = args.run_dir.resolve()
    if not run_dir.is_dir():
        parser.error(f"{run_dir} is not a directory")

    figs_dir = run_dir / "figs"
    figs_inputs_dir = figs_dir / "inputs"

    model = _load_model(run_dir)
    _patch_legacy_options(model)
    seed = _read_seed(run_dir)
    _seed_global_rng(seed)

    requested = _filter_renderable(model, list(args.figs))
    if not requested:
        log.warning("no figures to render")
        return 0

    needs_align_mod = bool(set(requested) & (_NEEDS_ALIGN_MOD | _NEEDS_STATS))
    needs_stats = bool(set(requested) & _NEEDS_STATS)

    align_path: Path | None = None
    if needs_align_mod:
        if args.synthetic_alignment is not None:
            align_path = args.synthetic_alignment.resolve()
        else:
            align_path = _autodiscover_synthetic(run_dir)
            if align_path is None:
                parser.error(
                    "the requested figures need a synthetic alignment. Run "
                    "`bash scripts/sample_sbm.sh <run_dir>` first, then pass "
                    "--synthetic-alignment PATH (or render only "
                    + ", ".join(sorted(set(ALL_FIGS) - _NEEDS_ALIGN_MOD - _NEEDS_STATS))
                    + ")."
                )
            log.info("auto-selected synthetic alignment: %s", align_path)

    # Activate lab style. Wrapped because the user may not have the
    # lab-paper stylesheet installed; falling back to mpl defaults is
    # acceptable for routine runs.
    try:
        plt.style.use("lab-paper")
    except (OSError, ValueError):
        log.info("'lab-paper' stylesheet not available; using matplotlib defaults")

    align_mod = None
    stats = None
    if align_path is not None:
        align_mod = _load_align_mod(align_path, model)
        model["align_mod"] = align_mod
    if needs_stats:
        stats = _ensure_stats(model, align_mod, figs_inputs_dir)

    run_id = run_dir.name
    written: list[Path] = []
    rendered_names: list[str] = []
    try:
        for name in requested:
            log.info("rendering %s", name)
            paths = _render_one(name, model, stats, figs_dir, run_id=run_id)
            if paths:
                rendered_names.append(name)
                written.extend(paths)
    finally:
        # Record provenance even if rendering raised partway through, so a
        # half-populated figs/ still has a sources.json identifying which
        # model + alignment produced what landed on disk.
        _write_sources_json(
            figs_inputs_dir,
            run_dir=run_dir,
            model_path=run_dir / "model.npy",
            align_path=align_path,
            figures=rendered_names,
        )

    log.info("wrote %d figure(s) under %s", len(written), figs_dir)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
